# Generated by Django 3.1.4 on 2021-02-11 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='İSİM')),
                ('sex_category', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Çocuk', 'Çocuk')], max_length=60, null=True, verbose_name='CİNSİYET')),
                ('price', models.FloatField(verbose_name='FİYAT')),
                ('marka', models.CharField(max_length=50, null=True, verbose_name='MARKA')),
                ('image', models.FileField(null=True, upload_to='', verbose_name='FOTOĞRAF')),
                ('category', models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('Kaban*Mont', 'Kaban/Mont'), ('Kazak*Hırka', 'Kazak/Hırka'), ('Pantolon', 'Pantolon'), ('Jeans', 'Jeans'), ('Ceket', 'Ceket'), ('Gömlek', 'Gömlek'), ('Takım_Elbise', 'Takım Elbise'), ('Şort*Kapri', 'Şort/Kapri'), ('Tişört', 'Tişört'), ('İç Giyim/Çorap', 'İç Giyim/Çorap'), ('Elbise', 'Elbise'), ('Tayt', 'Tayt'), ('Plaj_Giyim', 'Plaj Giyim'), ('Çanta/Aksesuar', 'Çanta/Aksesuar'), ('Ayakkabı', 'Ayakkabı')], max_length=30, verbose_name='KATEGORİ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('rating_total', models.FloatField(blank=True, null=True, verbose_name='ortalama puan')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='SATICI')),
            ],
            options={
                'ordering': ['-rating_total'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='malzeme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ALICI')),
            ],
        ),
    ]
