# Generated by Django 3.1.4 on 2021-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ornek',
            field=models.JSONField(null=True),
        ),
    ]
