# Generated by Django 3.1.4 on 2021-02-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_ornek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ornek',
            new_name='rating',
        ),
    ]
