# Generated by Django 3.1.4 on 2021-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210211_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.JSONField(default={}, null=True),
        ),
    ]
