# Generated by Django 3.1.4 on 2021-02-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_newusermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUserModel',
        ),
    ]
