# Generated by Django 3.1.4 on 2021-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_newusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
