# Generated by Django 3.1.4 on 2021-02-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210211_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='İnfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=60)),
                ('tel_no', models.CharField(max_length=25)),
                ('e_mail', models.EmailField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('post_code', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı')),
            ],
        ),
        migrations.DeleteModel(
            name='İnfo',
        ),
    ]
