# Generated by Django 3.1.4 on 2021-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210213_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇nfos',
            name='adress_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
